# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
    python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: pretty-format-json
      - id: check-yaml
      - id: debug-statements
      - id: check-added-large-files
      - id: check-docstring-first
        name: check docstring is first
        description: checks a common error of defining a docstring after code.
        entry: check-docstring-first
        language: python
        types: [ python ]

#  - repo: https://github.com/psf/black
#    rev: 21.9b0
#  - repo: https://github.com/pycqa/flake8
#    rev: 4.0.1
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        language_version: python3
        types: [ python ]

      - id: flake8
        name: flake8
        entry: flake8
        language: python
        language_version: python3
        types: [python]

#-   repo: https://github.com/pycqa/pydocstyle
#    rev: 6.1.1  # pick a git hash / tag to point to
#    hooks:
#    -   id: pydocstyle
#        args:
#          - --ignore=D100,D203,D405

#-   repo: https://github.com/asottile/pyupgrade
#    rev: v2.29.0
#    hooks:
#    -   id: pyupgrade
#        args: [ --py3-plus ]
#        verbose: true
