version: '3.9'
services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        environment:
            FASTAPI_ENV: development
    redis:
        image: "redis:alpine"
